### ISSUE TITLE
Presque impossible d'importer un projet back-end

### ISSUE THREAD

**Issue by QuentinBubu** [MickaelFerri25/Made#12]
Lorsque nous voulons importer un projet en back-end, nous sommes obligé de mettre un lien Figma et une image, or, bah c'est du back-end :p

**Comment by MickaelFerri25** [comment]
En effet, nous avons pas pensé à cela, garde ton projets bien au chaud et nous changeront cela dans la V2.
je suis justement entrain de recoder le formulaire pour palier à ce problème, désoler pour la gêne occasionné.
A très vite sur Made
