### ISSUE TITLE
Mot de passe oublié?

### ISSUE THREAD

**Issue by QuentinBubu** [MickaelFerri25/Made#18]
Le bouton mot de passe oublié ne fonctionne pas :/
Lorsque l'on tente d'y accéder, nous obtenons 
> Cannot GET /view/pages/connexion.html 

Quel dommage... :(

**Comment by MickaelFerri25** [comment]
Bonjour à toi,
En effet nous avons pas encore fait de page pour faire cette action mais tous ça arriveras dans la V2.
à très vite sur Made !
