### ISSUE TITLE
Tout les TPs

### ISSUE THREAD

**Issue by QuentinBubu** [MickaelFerri25/Made#7]
Une fonction permettant d'afficher tout les TPs, pratique quand on ne sait pas dans lequel se lancer :)

**Comment by MickaelFerri25** [comment]
Je ne compte pas faire ça, tous simplement car je considère que ma façon de faire est plus organisé donc plus pratique pour l'utilisateur qui sait ce qu'il veut et aussi plus pratique niveaux UX / UI pour la nouvelle version de Made.
