### ISSUE TITLE
Système d'avis

### ISSUE THREAD

**Issue by QuentinBubu** [MickaelFerri25/Made#8]
Mettre pour les TPs un système d'avis et/ou de notation (style like ou note) pour voir ce qui a plus ou pas, les éventuelles suggestions...
De même pour le site, un retour utilisateur est bien pour le développement

**Comment by MickaelFerri25** [comment]
Bonjour à vous !
Oui, un système d'avis est prévue pour la nouvelle version de Made.
L'équipe de made vous remercie pour votre retour.
